AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  get-cognito-user-credentials

Resources:
  GetCognitoUserCredentials:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-cognito-user-credentials/
      Handler: app.lambda_handler
      Runtime: python3.9
      FunctionName: get-cognito-user-credentials
      Architectures:
        - x86_64
